-- Advanced per-bot MM / Volume parameters
ALTER TABLE "MarketMakingConfig"
ADD COLUMN     "mmRepriceMs" INTEGER NOT NULL DEFAULT 15000,
ADD COLUMN     "mmRepricePct" DOUBLE PRECISION NOT NULL DEFAULT 0.01,
ADD COLUMN     "mmPriceEpsPct" DOUBLE PRECISION NOT NULL DEFAULT 0.005,
ADD COLUMN     "mmQtyEpsPct" DOUBLE PRECISION NOT NULL DEFAULT 0.02,
ADD COLUMN     "mmInvAlpha" DOUBLE PRECISION NOT NULL DEFAULT 0.1;

ALTER TABLE "VolumeConfig"
ADD COLUMN     "volCooldownMs" INTEGER NOT NULL DEFAULT 60000,
ADD COLUMN     "volActiveTtlMs" INTEGER NOT NULL DEFAULT 20000,
ADD COLUMN     "volMmSafetyMult" DOUBLE PRECISION NOT NULL DEFAULT 1.5,
ADD COLUMN     "volLastBandPct" DOUBLE PRECISION NOT NULL DEFAULT 0.0001,
ADD COLUMN     "volInsideSpreadPct" DOUBLE PRECISION NOT NULL DEFAULT 0.00005,
ADD COLUMN     "volLastMinBumpAbs" DOUBLE PRECISION NOT NULL DEFAULT 0.00000001,
ADD COLUMN     "volLastMinBumpPct" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "volBuyTicks" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "volSellTicks" INTEGER NOT NULL DEFAULT 2;
