// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/api-keys" | "/admin/exchanges" | "/admin/indicator-settings" | "/admin/prediction-refresh" | "/admin/smtp" | "/admin/telegram" | "/admin/users" | "/bots" | "/bots/[id]" | "/bots/[id]/price-support" | "/bots/[id]/settings" | "/bots/new" | "/calendar" | "/dashboard" | "/help" | "/login" | "/predictions" | "/register" | "/reset-password" | "/settings" | "/settings/audit" | "/settings/exchange-accounts" | "/settings/global-defaults" | "/settings/notifications" | "/settings/roles" | "/settings/setup" | "/settings/subscription" | "/settings/users" | "/trade" | "/trading-desk"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/api-keys": {}
  "/admin/exchanges": {}
  "/admin/indicator-settings": {}
  "/admin/prediction-refresh": {}
  "/admin/smtp": {}
  "/admin/telegram": {}
  "/admin/users": {}
  "/bots": {}
  "/bots/[id]": { "id": string; }
  "/bots/[id]/price-support": { "id": string; }
  "/bots/[id]/settings": { "id": string; }
  "/bots/new": {}
  "/calendar": {}
  "/dashboard": {}
  "/help": {}
  "/login": {}
  "/predictions": {}
  "/register": {}
  "/reset-password": {}
  "/settings": {}
  "/settings/audit": {}
  "/settings/exchange-accounts": {}
  "/settings/global-defaults": {}
  "/settings/notifications": {}
  "/settings/roles": {}
  "/settings/setup": {}
  "/settings/subscription": {}
  "/settings/users": {}
  "/trade": {}
  "/trading-desk": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
