// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/admin/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/api-keys">> = Specific
  const handler = {} as typeof import("../../app/admin/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/exchanges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/exchanges">> = Specific
  const handler = {} as typeof import("../../app/admin/exchanges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/indicator-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/indicator-settings">> = Specific
  const handler = {} as typeof import("../../app/admin/indicator-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/prediction-refresh/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/prediction-refresh">> = Specific
  const handler = {} as typeof import("../../app/admin/prediction-refresh/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/smtp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/smtp">> = Specific
  const handler = {} as typeof import("../../app/admin/smtp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/telegram/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/telegram">> = Specific
  const handler = {} as typeof import("../../app/admin/telegram/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bots/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bots/[id]">> = Specific
  const handler = {} as typeof import("../../app/bots/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bots/[id]/price-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bots/[id]/price-support">> = Specific
  const handler = {} as typeof import("../../app/bots/[id]/price-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bots/[id]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bots/[id]/settings">> = Specific
  const handler = {} as typeof import("../../app/bots/[id]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bots/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bots/new">> = Specific
  const handler = {} as typeof import("../../app/bots/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bots">> = Specific
  const handler = {} as typeof import("../../app/bots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../app/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/predictions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/predictions">> = Specific
  const handler = {} as typeof import("../../app/predictions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/audit">> = Specific
  const handler = {} as typeof import("../../app/settings/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/exchange-accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/exchange-accounts">> = Specific
  const handler = {} as typeof import("../../app/settings/exchange-accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/global-defaults/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/global-defaults">> = Specific
  const handler = {} as typeof import("../../app/settings/global-defaults/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/notifications">> = Specific
  const handler = {} as typeof import("../../app/settings/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/roles">> = Specific
  const handler = {} as typeof import("../../app/settings/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/setup">> = Specific
  const handler = {} as typeof import("../../app/settings/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/subscription">> = Specific
  const handler = {} as typeof import("../../app/settings/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/users">> = Specific
  const handler = {} as typeof import("../../app/settings/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trade">> = Specific
  const handler = {} as typeof import("../../app/trade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trading-desk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trading-desk">> = Specific
  const handler = {} as typeof import("../../app/trading-desk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
