export const HYPERLIQUID_DEFAULT_REST_BASE_URL = "https://api.hyperliquid.xyz";
export const HYPERLIQUID_TESTNET_REST_BASE_URL = "https://api.hyperliquid-testnet.xyz";

export const HYPERLIQUID_DEFAULT_TIMEOUT_MS = 12_000;
export const HYPERLIQUID_DEFAULT_RETRY_ATTEMPTS = 3;
export const HYPERLIQUID_DEFAULT_RETRY_BASE_DELAY_MS = 250;

export const HYPERLIQUID_DEFAULT_PRODUCT_TYPE = "USDT-FUTURES" as const;
export const HYPERLIQUID_DEFAULT_MARGIN_COIN = "USDC";

export const HYPERLIQUID_ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";
